---
# The world for the items to spawn the drop party in.
World: world
# Time before drop party starts in minutes
Time: 4320
# Duration of the drop party in seconds
Duration: 120
# Messages.
Message:
  Started: §7[§3§lDropParty§l§7] §aDropPary is starting! §aDo §b/spawn§a to join the §3DropParty§r
  Ended: §7[§3§lDropParty§l§7] §cDropPary has ended! §aAnother §3DropParty will take place in 3 days at 
  Countdown: §7[§3§lDropParty§l§7] §aDropPary is starting! §aDo §b/spawn§a to join the §3DropParty§r
# Broadcast: "Coming soon." this will break since the task can not handle without another rewrite.
# Popups creates a popup above the xp bar
Popup:
  Enabled: true
  Message: §7[§3§lDropParty§l§7] §aDropPary is starting! §aDo §b/spawn§a to join the §3DropParty§r
# Coordinates for it to spawn at
Coordinates:
  X: 18
  Y: 86
  Z: 15
Items:
- 35
- 35:1
- 35:2
- 35:3
- 35:4
- 35:6
- 35:5
- 35:7
- 35:8
- 35:9
- 35:10
- 35:11
- 35:12
- 35:13
- 35:14
- 35:15
- 1
- 2
- 3
- 4
- 14
- 15
- 16
- 56
- 5
- 5:1
- 5:2
- 5:3
- 5:4
- 5:5
- 6
- 6:1
- 6:2
- 6:3
- 6:4
- 6:5
- 9
- 11
- 13
- 19
- 38
- 38:1
- 38:2
- 38:3
- 38:4
- 38:5
- 38:6
- 38:7
- 38:8
- 39
- 40
- 43:4
- 155
- 76
- 79
- 80
- 138
...

